// File generated by FlutterFire CLI.
// This file should be updated when the user configures Firebase via Dreamflow

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-D8ojJnLDisxKiM1sk2DJ1slvEtuTsfw',
    appId: '1:656360637630:web:bc50c8be4d6f6a005d4aef',
    messagingSenderId: '656360637630',
    projectId: 'spendrail',
    authDomain: 'spendrail.firebaseapp.com',
    storageBucket: 'spendrail.firebasestorage.app',
    measurementId: 'G-GH94DK9EZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6SMyar7FIyY8tH6PFMKdtVoPrDlA__MM',
    appId: '1:656360637630:android:a28665ce076d43b25d4aef',
    messagingSenderId: '656360637630',
    projectId: 'spendrail',
    storageBucket: 'spendrail.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs05nEgKlfJmg3fDWIJCD_2tRdZWBuxrY',
    appId: '1:656360637630:ios:28e868fae75996f45d4aef',
    messagingSenderId: '656360637630',
    projectId: 'spendrail',
    storageBucket: 'spendrail.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.spendrail.workerapp',
  );
}